services:
  db:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5442:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - backend-network

  opo_reporter:
    image: reporting-service:1.0.0
    command: python -m app
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./service_account.json:/app/src/service_account.json
    environment:
      - GOOGLE_SHEETS_ID=${GOOGLE_SHEETS_ID}
      - YAML_PATH=/app/config.yaml
    networks:
      - backend-network
    restart: always

networks:
  backend-network:
    driver: bridge
